spring.application.name=swift

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_swift_monitoring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=swift
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.error.include-message=always
server.error.include-stacktrace=always

# Dossiers batch (SOP par défaut)
file.in=IN_SOP
file.saved=SAVE_SOP
file.error=ERREUR_SOP


# Dossier d'entrée pour les messages SOP (.xml)
input.mx.directory=IN_SOP

# Dossier d'entrée pour les messages SAA (.ack)
input.ack.directory=IN_SAA

# Dossiers sortie / reçu (VirementRecu + MessageRecu) 
output.saa.directory=OUT_SAA
output.sop.directory=OUT_SOP

# Scheduler : délai avant le 1er passage (ms), puis délai entre chaque passage
batch.poll.initial.delay.ms=1000
batch.poll.delay.ms=10000
