spring.application.name=swift

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_swift_monitoring
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=swift
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.error.include-message=always
server.error.include-stacktrace=always

file.in=IN_SOP
file.saved=SAVE_SOP
file.error=ERREUR_SOP

input.mx.directory=SOP_2/IN_SOP,SOP_T/IN_SOP,SOP_3/IN_SOP,MAJDAA/IN_SOP,SOPtest/IN_SOP

input.ack.directory=SAA/IN_SAA

output.saa.directory=SAA/OUT_SAA
output.sop.directory=SOP_2/OUT_SOP,SOP_T/OUT_SOP,SOP_3/OUT_SOP,MAJDAA/OUT_SOP,SOPtest/OUT_SOP

# Scheduler : délai avant le 1er passage (ms), puis délai entre chaque passage
batch.poll.initial.delay.ms=1000
batch.poll.delay.ms=10000
